name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bug"
  - title: "Improvements"
    labels:
      - "improvement"
      - "refactor"
  - title: "Maintenance"
    labels:
      - "chore"
      - "dependencies"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'

exclude-labels:
  - "skip-changelog"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
      - "feature"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bug"
  default: patch

autolabeler:
  - label: "feature"
    title:
      - "/^[Aa]dd /i"
      - "/^[Ff]eat/i"
  - label: "fix"
    title:
      - "/^[Ff]ix/i"
  - label: "chore"
    title:
      - "/^[Cc]hore/i"
      - "/^[Rr]emove/i"
  - label: "improvement"
    title:
      - "/^[Rr]efactor/i"
      - "/^[Rr]efine/i"
      - "/^[Uu]nify/i"
      - "/^[Uu]pdate/i"
      - "/^[Ii]mprove/i"

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
